spring:
  application:
    name: MONGO-TEST

  data:
    mongodb:
      host: 192.168.0.6
      port: 27017
      database: Muller



  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"



  health:
    probes:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

jwt:
  secret: tokensecret
  expiry:  3600000


